name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      playwright:
        image: mcr.microsoft.com/playwright:v1.37.0-focal
        options: --ipc=host
        ports:
          - 8080:8080

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.4.1'

    - name: Install dependencies
      run: npm ci

    - name: Run Playwright Tests on Push
      if: github.event_name == 'push'
      env:
        CI: true
        CI_WORKERS: 4
        CI_RETRIES: 1
        CI_BROWSER: chromium
      run: npm run test:smoke

    - name: Run Playwright Tests on Pull Request
      if: github.event_name == 'pull_request'
      env:
        CI: true
        CI_WORKERS: 4
        CI_RETRIES: 2
        CI_BROWSER: chromium
      run: npm run test
